name: backend
description: A sample command-line application.

environment:
  sdk: ^3.7.0

dependencies:

# Archive
  archive: ^4.0.5

# Mime
  mime: ^2.0.0

# Path
  path: ^1.9.1

# Shelf
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.1
  shelf_multipart: ^2.0.0
  shelf_router: ^1.1.4

# Sqlite3
  sqlite3: ^2.7.5
 

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
