name: dashboard
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5+115

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

# Connectivity Plus
  connectivity_plus: ^6.1.0

# File Piker
  file_picker: ^10.0.0

# Intl
  intl: ^0.19.0

# Geo
  geolocator: ^13.0.4

# Google  
  google_fonts: ^6.2.1

# HTTP  
  http: ^1.2.2
  http_parser: ^4.1.2

# Package Info
  package_info_plus: ^8.3.0

# Provider
  provider: ^6.1.4

# Shared Preferences
  shared_preferences: ^2.5.3

# Shimer
  shimmer: ^3.0.0

# Url Launcher
  url_launcher: ^6.3.1
  
# Window Manager
  window_manager: ^0.4.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  msix: ^3.16.8

flutter:
  uses-material-design: true

  assets:
    - assets/img/

msix_config:
  display_name: Dashboard ShopTem
  publisher_display_name: Hendril Mendes
  identity_name: com.github.hendrilmendes.shop.dashboard
  logo_path: assets/img/ic_launcher.png
  icons_background_color: transparent
  capabilities: internetClient, location, privateNetworkClientServer
  signtool_options: /fd SHA256 /f "C:\Users\Hendril\Documents\GitHub\Key App.pfx" /p Hendril@123
